name: Deploy

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  archive-and-release:
    uses: .github/workflows/archive-and-release.yml
    with:
      # Pass any inputs if your reusable workflow expects them
    secrets: inherit

  deploy:
    runs-on: ubuntu-latest
    needs: archive-and-release

    steps:
    - name: Download release ZIP artifact
      uses: actions/download-artifact@v3
      with:
        name: node-project-archive
        path: release

    - name: Unzip release artifact
      run: unzip release/release.zip -d /var/www/dist

    - name: Install dependencies
      run: |
        cd /var/www/dist
        npm install --production

    - name: Deploy application
      run: |
        # Add your deployment commands here
        echo "Deploying application..."
